apiVersion: v1
appVersion: 0.5.2
description: Rancher demo application, web UI showing scale of containers
name: rancher-demo
version: 0.5.2
icon: https://udemy-images.udemy.com/course/750x422/1527740_a494.jpg
